"""Public exception types for the LogRhythm SDK.

This is the SDK's single public exception surface, per SPEC-007's Public API
decision: every public exception is provided from here, never from
``logrhythm_sdk.core`` directly. This module is a thin facade; see
:mod:`logrhythm_sdk.core.exceptions` for the actual class definitions.
"""

from logrhythm_sdk.core.exceptions import (
    ApiError,
    ApiNotConfiguredError,
    ApiValidationError,
    AuthenticationError,
    AuthorizationError,
    ClientClosedError,
    ClientInitializationError,
    ClientResponseError,
    ClientStateError,
    ConfigurationError,
    ConfigurationFormatError,
    ConfigurationSourceError,
    ConfigurationValidationError,
    ConflictError,
    LoggingConfigurationError,
    LogRhythmSdkError,
    ModelError,
    RateLimitError,
    RequestSerializationError,
    RequestValidationError,
    ResourceNotFoundError,
    ResponseDecodingError,
    ResponseValidationError,
    SerializationError,
    ServerResponseError,
    TransportConnectionError,
    TransportError,
    TransportProtocolError,
    TransportRequestError,
    TransportTimeoutError,
    TransportTlsError,
    UnexpectedRedirectError,
)

__all__ = [
    "ApiError",
    "ApiNotConfiguredError",
    "ApiValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "ClientClosedError",
    "ClientInitializationError",
    "ClientResponseError",
    "ClientStateError",
    "ConfigurationError",
    "ConfigurationFormatError",
    "ConfigurationSourceError",
    "ConfigurationValidationError",
    "ConflictError",
    "LogRhythmSdkError",
    "LoggingConfigurationError",
    "ModelError",
    "RateLimitError",
    "RequestSerializationError",
    "RequestValidationError",
    "ResourceNotFoundError",
    "ResponseDecodingError",
    "ResponseValidationError",
    "SerializationError",
    "ServerResponseError",
    "TransportConnectionError",
    "TransportError",
    "TransportProtocolError",
    "TransportRequestError",
    "TransportTimeoutError",
    "TransportTlsError",
    "UnexpectedRedirectError",
]
